use_frameworks!

target 'SwiftCandy_Example' do
  pod 'SwiftCandy', :path => '../'

  target 'SwiftCandy_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
